dist: trusty
sudo: false

language: scala
services:
  - docker

jdk:
  - openjdk8

scala:
   - 2.11.11

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt


before_install:
 - docker run --privileged -d -p 9432:9432 --name bblfsh bblfsh/bblfshd
 - docker exec -it bblfsh bblfshctl driver install --all
 - sudo apt-get update
 - sudo apt-get install -y --no-install-recommends clang g++ gcc gcc-multilib libc6-dev libc6-dev-i386 mingw-w64 patch xz-utils libxml2-dev

env:
  global:
   - OSXCROSS_PACKAGE="osxcross_3034f7149716d815bc473d0a7b35d17e4cf175aa.tar.gz"
   - OSXCROSS_URL="https://github.com/bblfsh/client-scala/releases/download/v1.5.2/${OSXCROSS_PACKAGE}"

install:
 - cd ${HOME}
 - curl -sSL ${OSXCROSS_URL} | tar -C ${HOME} -xzf - 

script:
 - cd $TRAVIS_BUILD_DIR
 - ./sbt assembly test
 - if [[ -z "$TRAVIS_TAG" ]]; then echo "Skipping this build for non-tag builds."; exit 0; fi
 - ./sbt publishLocal
 - openssl aes-256-cbc -K $encrypted_97aef7f4ae04_key -iv $encrypted_97aef7f4ae04_iv -in key.asc.enc -out key.asc -d
 - gpg --no-default-keyring --primary-keyring ./project/.gnupg/pubring.gpg --secret-keyring ./project/.gnupg/secring.gpg --keyring ./project/.gnupg/pubring.gpg --fingerprint --import key.asc
 - ./sbt publishSigned
 - ./sbt sonatypeRelease

after_failure:
 - docker logs bblfsh
